# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - shopease-bula

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        working-directory: ./Backend
        run: npm ci --production

      - name: Create deployment package
        run: |
          cd Backend
          zip -r ../release.zip . -x "*.git*" -x "*.env*"
          cd ..
          ls -la release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_43B33BA39B9C4870A97CEE94BCA96E03 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F29BA19920714066B685828268C203FC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3BABC885B35F4C8FA620D627CDD12BFC }}

      - name: Stop Azure Web App
        uses: azure/cli@v2
        with:
          inlineScript: |
            RG=$(az webapp list --query "[?name=='shopease-bula'].resourceGroup" -o tsv)
            az webapp stop --name shopease-bula --resource-group $RG

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'shopease-bula'
          slot-name: 'Production'
          package: release.zip
          clean: true

      - name: Start Azure Web App
        uses: azure/cli@v2
        with:
          inlineScript: |
            RG=$(az webapp list --query "[?name=='shopease-bula'].resourceGroup" -o tsv)
            az webapp start --name shopease-bula --resource-group $RG
